name: Importar Test Case

on:
  workflow_dispatch:
    inputs:
      featurepath:
        description: Ruta al archivo feature
        required: true
      project:
        description: Selecciona el proyecto
        required: true
        type: choice
        options:
        - '102030:Labs Test'
      validate:
        description: ¿Deseas validar existencias?
        type: boolean
        default: false
jobs:
  import_testcase:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: 🚀 Importar Test Case
      uses: "HERA_YOUR_ACTION_PATH"
      with:
        execute: import-testcase
        settings: "HERE_YOUR_CONFIG_DIR/settings.json"
        username: "HERE_YOUR_SECRET_KEY"
        secretkey: "HERE_YOUR_SECRET_KEY"
        filepath: ${{ inputs.featurepath }}
        project: ${{ inputs.project }}
        exists: ${{ inputs.validate }}
